### ISSUE TITLE
error from user

### ISSUE THREAD

**Issue by schriftgestalt** [harbortype/ShowSmoothNodeAngleAndProportion#15]
```
Details:
Traceback (most recent call last):

 File "GlyphsApp/GlyphsApp/plugins.py", line 1412, in raiseException_

 File "GlyphsApp/GlyphsApp/plugins.py", line 1240, in drawBackgroundWithOptions_

 File "plugin.py", line 430, in backgroundInViewCoords
   compatibleAngles = self.compatibleAngles(glyph, pathIndex, nodeIndex)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

 File "plugin.py", line 151, in compatibleAngles
   currentPath = layer.paths[pathIndex]
                 ~~~~~~~~~~~^^^^^^^^^^^

 File "GlyphsApp/GlyphsApp/__init__.py", line 613, in __GSProxyShapes__getitem__

IndexError: list index out of range

App:3.3-3311 Plugin:1.4-9 System:14.5.0
```

**Comment by harbortype** [comment]
I just pushed the commit df9c05e755c5f412168f67f5332e8c5e75732fd9 that should fix that.
